---
- hosts: all
  vars:
    samba_netbios_name: CLOSET
    samba_server_string: 'do not enter!!'
    samba_workgroup: WORKGROUP

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never
    samba_shares_root: /mnt/
    samba_shares:
      - name: storage
        guest_ok: yes
        writable: yes
  roles:
    - role: samba