---
- hosts: all
  vars:
    syncthing_address: 127.0.0.1:8080
    syncthing_listen: 127.0.0.1:22000
    syncthing_use_systemd: true
    syncthing_use_supervisor: false
    syncthing_use_ufw: false
  roles:
    - role: syncthing