---
- hosts: all
  vars:
    serf_architecture:
      x86_64: amd64
      i386:   386
      armv5l: arm
      armv6l: arm
      armv7l: arm
      arm64: arm64
    syncthing_version: 0.14.7
    syncthing_url: https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-{{ansible_system|lower}}-{{serf_architecture[ansible_architecture]}}-v{{syncthing_version}}.tar.gz
    syncthing_user: syncthing
    syncthing_address: 0.0.0.0:8080
    syncthing_listen: 0.0.0.0:22000
    syncthing_home: /home/syncthing
    syncthing_localannounce: true
    syncthing_globalannounce: true
    syncthing_upnp: true
    syncthing_use_ufw: true
    syncthing_use_systemd: true
    syncthing_use_supervisor: false
  tasks:

  - name: install deps
    dnf:
      name: libselinux-python
      state: latest
  - include: ../roles/syncthing/tasks/main.yml

